---
- name: Create file with content
  hosts: all
  gather_facts: yes

  tasks:
    - name: Create test file
      ansible.windows.win_copy:
        content: "File created from AWX"
        dest: "{{ ansible_env.USERPROFILE }}\\Desktop\\awx_file.txt"

    - name: Install Notepad++
      ansible.windows.win_package:
        path: https://github.com/notepad-plus-plus/notepad-plus-plus/releases/latest/download/npp.8.6.Installer.x64.exe
        arguments: /S
        state: present
