---
- name: Create file with content
  hosts: all
  gather_facts: no

  tasks:
    - name: Check for available Windows updates
      ansible.windows.win_updates:
        state: searched
      register: update_result

    - name: Show available updates
      debug:
        var: update_result
