---
- name: Create file with content
  hosts: all
  gather_facts: no

  tasks:
    - name: Create test file
      ansible.windows.win_copy:
        content: "File created from AWX"
        dest: "{{ ansible_env.USERPROFILE }}\\Desktop\\awx_file.txt"
